name: Docker deploy

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and Deploy on DigitalOcean server
      uses: applyboy/ssh-action@v0.1.2
      with: 
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        
        script: |
          docker pull ${{secrets.DOCKER_USER}}/fitpose
          docker tag ${{secrets.DOCKER_USER}}/fitpose:latest dokku/api:latest
          dokku tags:deploy api latest
